# Setup
title: Ben Goertz
url: https://suite22.github.io/blog/
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: Ben Goertz
  url: https://twitter.com/suite22

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Projects
    url: /projects
    
  - title: Blog
    url: /archive

  - title: About
    url: /about
