# Setup
title: Backbone
url: https://backbone-stories.github.io/website/
paginate: 1
paginate_path: "/page:num/"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Navbar page list
nav:
  - title: About
    url: /about

  - title: Stories
    url: /stories

# Conversion
markdown: kramdown

liquid:
  error_mode: strict

# Markdown Processors
kramdown:
  auto_ids          : true
  toc_levels        : [1, 2, 3, 4]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : true