# Setup
title: Ben Goertz [DEBUG]
# Following the suggestion of this SO answer https://stackoverflow.com/a/37087102/5499522
# Serve locally using the command:
# bundle exec jekyll serve --config _config.yml,_config_debug.yml
baseurl: ""

# This is a hack because the relative path differs between local and github pages.
# Navbar page list
nav:
  - title: Projects
    url: /projects
    
  - title: Blog
    url: /archive

  - title: About
    url: /about